services:
  - type: web
    name: kotogram-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.7.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: kotogram-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://kotogram-backend.onrender.com
    autoDeploy: true 